name: doc_translation
description: A document translation app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  file_picker: ^5.5.0
  path_provider: ^2.1.5
  uuid: ^3.0.7
  flutter_pdfview: ^1.3.2       # For PDF preview
  cupertino_icons: ^1.0.2
  # For document text extraction
  archive: ^3.4.10             # For ZIP extraction (needed for DOCX)
  xml: ^6.3.0                 # For XML parsing (needed for DOCX)
  syncfusion_flutter_pdf: ^23.1.44


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true